SEAS/Enrollment/urls.py
from django.urls import path

from . import views

app_name = 'enrollment'
urlpatterns = [
    path('Enrollment-Expand', views.schoolWiseEnrollExpand, name='expanded'),
    path('Enrollment-Compact', views.schoolWiseEnrollCompact, name='compact')
]

SEAS/SEAS/urls.py
from django.contrib import admin
from django.urls import path, include

# from SEAS import revenue

urlpatterns = [
    path('', include('login.urls', namespace='login')),
    path('home/', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    
    # Fahim's stuff
    path( 'revenue/', include('revenue.urls', namespace='revenue')),

    # Suhailia's stuff
    path( 'Enrollment/', include('Enrollment.urls', namespace='enrollment')),

    # Shafayat's stuff
    path('databaseupdate/',include('databaseupdate.urls', namespace='update')),
    path('classroom_requirement/', include('classroom_requirement.urls', namespace='classReq')),
    path('resources/', include('resources.urls', namespace='resources')),
]

SEAS/databaseupdate/urls.py
from django.urls import path

from . import views
app_name = 'databaseupdate'
urlpatterns = [
    path('', views.upload_file, name='upload_file'),
]

SEAS/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
]

SEAS/resources/urls.py
from django.urls import path

from . import views
app_name = 'resources'
urlpatterns = [
    path('resource_usage', views.resourceUsage, name='Resource_Usage'),
    path('resource_comparison', views.resourceComp, name='Resource_Comparison')
]

SEAS/revenue/urls.py
from django.urls import path

from . import views

app_name = 'revenue'
urlpatterns = [
    path('', views.revenueMain, name='revenueMain'),
    path('iub', views.iubRevenue, name='iubRevenue'),
    path('sch', views.deptRevenue, name='schoolRevenue'),
]

SEAS/home/views.py
from django.shortcuts import render

def index(request):
    context = {

    }
    return render(request, 'home/home.html', context)

SEAS/home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %} 

{% block content %}
{% load static %} 
<style>
.card{
  background-color: rgb(206, 255, 178);
  overflow: hidden;
  padding: 15px;
}

.card:hover {
  background-color: rgb(149, 243, 94);
  border-radius: 15px;
  transform: scale(1.05);
}

.card-container-content {
  margin-top: 15px;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  gap: 15px;
}

.admin-btn-container {
  margin-top: 15px;
  display: flex;
  justify-content: center;
}

.card-img-top {
  height: 65px;
  margin-bottom: 10px;
}

.admin-btn {
  text-decoration: none;
  border-radius: 10px;
  padding: 10px;
  background-color: rgb(99, 99, 209);
  color: white;
}

.admin-btn:hover {
  background-color: rgb(80, 80, 214);
  color: white;
  transform: scale(1.05);
}
</style>
<div class="card-container-content">
  <div class="card">
    <img class="card-img-top" src="{% static 'assets/class-req.svg' %}" alt="Card image cap">
    <div class="">
      <h5 class="card-title">Classroom Requirements</h5>
      <p class="card-text">View classroom requirement summary and percentage distribution of classrooms per class size pie chart.</p>
      <a class="stretched-link" href="{% url 'classReq:classReq' %}">
      </a>
    </div>
  </div>
  
  <div class="card">
    <img class="card-img-top" src="{% static 'assets/enrollment-1.svg' %}" alt="Card image cap">
    <div class="">
      <h5 class="card-title">Enrollment Information (Compact)</h5>
      <p class="card-text">View comparison of the number of sections offered across schools for a range of class sizes.</p>
      <a class="stretched-link" href="{% url 'enrollment:compact' %}">
      </a>
    </div>
  </div>
  

  <div class="card">
    <img class="card-img-top" src="{% static 'assets/resources.svg' %}" alt="Card image cap">
    <div class="">
      <h5 class="card-title">Usage Of The Resources</h5>
      <p class="card-text"> Compare average room capacity per room vs. average enrollment per course</p>
      <a class="stretched-link" href="{% url 'resources:Resource_Usage' %}">
      </a>
    </div>
  </div>
  

  <div class="card">
    <img class="card-img-top" src="{% static 'assets/course.svg' %}" alt="Card image cap">
    <div class="">
      <h5 class="card-title">Availability and course offering comparison</h5>
      <p class="card-text">View available classrooms summary. Compare available rooms of different capacities vs the required number between semesters</p>
      <a class="stretched-link" href="{% url 'resources:Resource_Comparison' %}">
      </a>
    </div>
  </div>

    
  <div class="card">
    <img class="card-img-top" src="{% static 'assets/enrollment-2.svg' %}" alt="Card image cap">
    <div class="">
      <h5 class="card-title">Enrollment Information (Expanded)</h5>
      <p class="card-text">View enrollment breakdown incremented by 1 for all schools</p>
      <a class="stretched-link" href="{% url 'enrollment:expanded' %}">
      </a>
    </div>
  </div>
  
  
  <div class="card">
    <img class="card-img-top" src="{% static 'assets/revenue-iub.svg' %}" alt="Card image cap">
    <div class="">
      <h5 class="card-title">Revenue Of IUB</h5>
      <p class="card-text">View historical revenue breakdown by school of IUB.</p>
      <a class="stretched-link" href="{% url 'revenue:iubRevenue' %}">
      </a>
    </div>
  </div>
  
  
  <div class="card">
    <img class="card-img-top" src="{% static 'assets/revenue-school.svg' %}" alt="Card image cap">
    <div class="">
      <h5 class="card-title">Revenue Of School</h5>
      <p class="card-text">View historical revenue breakdown of all departments of a selected school </p>
      <a class="stretched-link" href="{% url 'revenue:schoolRevenue' %}">
      </a>
    </div>
  </div>
  
  
  <div class="card">
    <img class="card-img-top" src="{% static 'assets/update-database.svg' %}" alt="Card image cap">
    <div class="">
      <h5 class="card-title">Add New Semester Data</h5>
      <p class="card-text">Upload a new tally sheet to update database.</p>
      <a class="stretched-link" href="{% url 'update:upload_file' %}"></a>
    </div>
  </div>
</div>
<div class="admin-btn-container">
  <a class="admin-btn" href="{% url 'admin:index' %}">
    Administration
  </a>
</div>
{% endblock content%}