SEAS/SEAS/urls.py
from django.contrib import admin
from django.urls import path, include

# from SEAS import revenue

urlpatterns = [
    path('', include('login.urls', namespace='login')),
    path('home/', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    
    # Fahim's stuff
    path( 'revenue/', include('revenue.urls', namespace='revenue')),

    # Suhailia's stuff
    path( 'Enrollment/', include('Enrollment.urls', namespace='enrollment')),

    # Shafayat's stuff
    path('databaseupdate/',include('databaseupdate.urls', namespace='update')),
    path('classroom_requirement/', include('classroom_requirement.urls', namespace='classReq')),
    path('resources/', include('resources.urls', namespace='resources')),
]

SEAS/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
]

SEAS/login/urls.py
from django.urls import path

from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='login'),
    path('home/logout', views.logout, name="logout"),
]

SEAS/resources/urls.py
from django.urls import path

from . import views
app_name = 'resources'
urlpatterns = [
    path('resource_usage', views.resourceUsage, name='Resource_Usage'),
    path('resource_comparison', views.resourceComp, name='Resource_Comparison')
]

SEAS/revenue/urls.py
from django.urls import path

from . import views

app_name = 'revenue'
urlpatterns = [
    path('', views.revenueMain, name='revenueMain'),
    path('iub', views.iubRevenue, name='iubRevenue'),
    path('sch', views.deptRevenue, name='schoolRevenue'),
]

SEAS/templates/School-Wise-Enroll-Expand.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Enrollment Expanded</title>
    <style>
        table, th, td {
          border: 1px solid white;
          border-collapse: collapse;
        }
        th {
          text-align: center;
          background-color: #96D4D4;
        }
        td {
            text-align: center;
            background-color: #96D4D4;
        }
        </style>
</head>
<body>
    <caption>School Wise Enrollment</caption>
    <table style="width:50%">
        ​​<thead>
            <tr> <th colspan="7">SPRING</th></tr>
            </thead>
            <thead>
            <tr>
            ​    {% for colName in labels %}​
                    <th>​{{colName}}​</th>
            ​    {% endfor %} 
            ​</tr> 
        </thead>
        <tbody>
            {% for row in data %} 
 ​            ​<tr>
                {% for item in row %} 
    ​                ​​<td>​{{item}}​</td> 
    ​            {% endfor %}
            </tr>
 ​                {% endfor %}
        </tbody> 
    </table>
    
</body>
</html>

SEAS/templates/School-Wise-Enrollment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Enrollment Expanded</title>
    <style>
        table, th, td {
          border: 1px solid white;
          border-collapse: collapse;
        }
        th {
          text-align: center;
          background-color: #96D4D4;
        }
        td {
            text-align: center;
            background-color: #96D4D4;
        }
        </style>
</head>
<body>
    <caption>School Wise Enrollment</caption>
    <table style="width:50%">
        ​​<thead>
            <tr> <th colspan="7">SPRING</th></tr>
            </thead>
            <thead>
            <tr>
            ​    {% for colName in labels %}​
                    <th>​{{colName}}​</th>
            ​    {% endfor %} 
            ​</tr> 
        </thead>
        <tbody>
            {% for row in data %} 
 ​            ​<tr>
                {% for item in row %} 
    ​                ​​<td>​{{item}}​</td> 
    ​            {% endfor %}
            </tr>
 ​                {% endfor %}
        </tbody> 
    </table>
    
</body>
</html>

SEAS/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <!-- ChartJS CDN -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
    <!-- For PieChart Percentage -->
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0/dist/chartjs-plugin-datalabels.min.js"></script>
    <!-- ChartJS Trendline -->
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{% block title %}{% endblock title %}</title>
  </head>

  <body class="body">
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    {% if user.is_authenticated %} {% include 'nav.html' %}
    <div class="container">{% block content %}{% endblock content %}</div>
    {% else %}
    <div class="not-logged-in">PLEASE <a href="/">LOGIN</a></div>
    {% endif %}
  </body>
</html>

SEAS/templates/nav.html
<script>
  $(document).ready(function () {
    $(".dropdown-submenu a.test").on("click", function (e) {
      $(this).next("ul").toggle();
      e.stopPropagation();
      e.preventDefault();
    });
  });
</script>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgb(214, 255, 241);">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SEAS</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'home:home' %}"
            method="get"
            >Home</a
          >
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Navigate Pages
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: rgb(214, 255, 241);">
            <li>
              <a class="dropdown-item" href="{% url 'update:upload_file' %}">
                Update Database
              </a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{% url 'classReq:classReq' %}">
                Classroom Requirements
              </a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{% url 'revenue:iubRevenue' %}">
                Revenue Of IUB
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'revenue:schoolRevenue' %}">
                Revenue Of School
              </a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{% url 'enrollment:expanded' %}">
                Enrollment Information (Expanded)
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'enrollment:compact' %}">
                Enrollment Information (Compact)
              </a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'resources:Resource_Usage' %}">
                Usage Of The Resources
              </a>
            </li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'resources:Resource_Comparison' %}">
                Availability and course offering comparison
              </a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{% url 'admin:index' %}">
                Administration
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'login:logout' %}"
            method="post"
            >Logout</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>